apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: hello-fastapi
  newName: sidneckel/hello-fastapi-k8s
  newTag: 38a5c57a0be24883baf2ed70a948a3550e79c2a3
