apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: hello-fastapi
  newName: sidneckel/hello-fastapi-k8s
  newTag: b23aa985d986d973c38e3b3ba0529607aca54351
