apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: hello-fastapi
  newName: sidneckel/hello-fastapi-k8s
  newTag: a46c58ca20391574cce3a49e1eb9bdbad150e78a
